### ISSUE TITLE
Does not work with clean RSpec 3.2

### ISSUE THREAD

**Issue by pkuczynski** [glebm/i18n-tasks#148]
When installed on clean project with RSpec 3.2, running tests raise an error

````
spec/i18n_spec.rb:4:in `<top (required)>': undefined method `describe' for main:Object (NoMethodError)
````

Changing ```describe``` to ```RSpec.describe``` in ```spec/i18n_spec.rb``` solves the problem.

**Comment by glebm** [comment]
Does Rspec.describe work with Rspec < 3.2? If so let's change it

**Comment by pkuczynski** [comment]
I would think so, but have no env to check.

**Comment by pkuczynski** [comment]
I found some extra explanation of the difference in both calls: 

http://stackoverflow.com/questions/24747448/rspec-describe-vs-describe

I think you can safely assume ```RSpec.describe``` will work everywhere and is more safe to use.
