### ISSUE TITLE
Sloppy gemspec: slop 4.0 causes crash

### ISSUE THREAD

**Issue by simplysoft** [glebm/i18n-tasks#118]
The gemspec specifies a dependency for slop >= 3.5.0, but i18n-tasks does not work with slop 4.0:

```
.../ruby/2.0.0/gems/i18n-tasks-0.7.10/bin/i18n-tasks:33:in `block in <top (required)>': undefined method `on' for main:Object (NoMethodError)
	from .../ruby/2.0.0/gems/slop-4.0.0/lib/slop/options.rb:33:in `initialize'
	from .../ruby/2.0.0/gems/slop-4.0.0/lib/slop.rb:24:in `new'
	from .../ruby/2.0.0/gems/slop-4.0.0/lib/slop.rb:24:in `parse'
	from .../ruby/2.0.0/gems/i18n-tasks-0.7.10/bin/i18n-tasks:32:in `<top (required)>'
	from .../ruby/2.0.0/bin/i18n-tasks:23:in `load'
	from .../ruby/2.0.0/bin/i18n-tasks:23:in `<main>'
```
Manually locking slop to 3.6 version did fix it

**Comment by einpaule** [comment]
Same problem for me, created pull request:

https://github.com/glebm/i18n-tasks/pull/121

**Comment by Florian95** [comment]
:+1:

**Comment by lacco** [comment]
+1 for merging this, adding ```gem 'slop', '~> 3.5'``` to my Gemfile fixed this for the moment.

**Comment by glebm** [comment]
Released v0.7.11 with #121 merged. Sorry about the delay! :ship:
