### ISSUE TITLE
Problem with 0.8.0

### ISSUE THREAD

**Issue by atipugin** [glebm/i18n-tasks#142]
0.8.0 doesn't work with rails 4.2.1. ```i18n-tasks normalize``` fails with following error:

```shell
vendor/bundle/gems/i18n-tasks-0.8.0/lib/i18n/tasks/data/router/pattern_router.rb:51:in `compile_routes': undefined method `map' for nil:NilClass (NoMethodError)```

**Comment by glebm** [comment]
Possibly related: #141

**Comment by glebm** [comment]
Is this fixed in [v0.8.1](https://github.com/glebm/i18n-tasks/releases/tag/v0.8.1)?

**Comment by glebm** [comment]
The issue is that the `write: ` setting is `nil` in the new config template.

**Comment by glebm** [comment]
Should be fixes in 0.8.2

**Comment by atipugin** [comment]
Yes, now it works :+1:
