### ISSUE TITLE
i18n-tasks seems not working with Rails/ActiveSupport 7 RC1

### ISSUE THREAD

**Issue by noefroidevaux** [glebm/i18n-tasks#400]
Hello,

Thank you for this great library!

Since the update to Rails 7 RC1 (with Ruby 3.0.3) I have the following error:

```
bash-5.1# i18n-tasks
/usr/local/bundle/gems/activesupport-7.0.0.rc1/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
        from /usr/local/bundle/gems/activesupport-7.0.0.rc1/lib/active_support/xml_mini.rb:103:in `backend='
        from /usr/local/bundle/gems/activesupport-7.0.0.rc1/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
        from /usr/local/bundle/gems/activesupport-7.0.0.rc1/lib/active_support/xml_mini.rb:11:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/bundle/gems/activesupport-7.0.0.rc1/lib/active_support/core_ext/hash/conversions.rb:3:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/bundle/gems/activesupport-7.0.0.rc1/lib/active_support/core_ext/hash.rb:3:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/bundle/gems/i18n-tasks-0.9.35/lib/i18n/tasks.rb:47:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/bundle/gems/i18n-tasks-0.9.35/lib/i18n/tasks/cli.rb:3:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/bundle/gems/i18n-tasks-0.9.35/bin/i18n-tasks:13:in `<top (required)>'
        from /usr/local/bundle/bin/i18n-tasks:25:in `load'
        from /usr/local/bundle/bin/i18n-tasks:25:in `<main>'
```

I'm not sure if it's a problem in this library or ActiveSupport. But the other libraries/tasks works well. On Rails 7 alpha 2, `i18n-tasks` worked well, it's only since the RC1.

**Comment by uxxman** [comment]
Having same issue since upgrading from 7.alpha2 to 7rc1

**Comment by alec-c4** [comment]
same situation for rails 7.0.0

```
Failures:

  1) I18n does not have missing keys
     Failure/Error: let(:missing_keys) { i18n.missing_keys }

     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./spec/i18n_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./spec/i18n_spec.rb:12:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:33:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:32:in `block (2 levels) in <top (required)>'

  2) I18n does not have unused keys
     Failure/Error: let(:unused_keys) { i18n.unused_keys }

     ArgumentError:
       wrong number of arguments (given 1, expected 0; required keyword: key)
     # <internal:kernel>:90:in `tap'
     # ./spec/i18n_spec.rb:8:in `block (2 levels) in <top (required)>'
     # ./spec/i18n_spec.rb:17:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:33:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:32:in `block (2 levels) in <top (required)>'

  3) I18n files are normalized
     Failure/Error: non_normalized = i18n.non_normalized_paths

     NoMethodError:
       undefined method `non_normalized_paths' for I18n::Tasks::BaseTask{"base_locale"=>"en", "internal_locale"=>"en", "locales"=>["en", "ru"], "data"=>{"adapter"=>"I18n::Tasks::Data::FileSystem", "read"=>["config/locales/%{locale}.yml", "config/locales/**/*.%{locale}.yml"], "write"=>["config/locales/%{locale}.yml"], "yaml"=>{"write"=>{"line_width"=>-1}}}, "search"=>{"paths"=>["app/"], "relative_roots"=>["app/controllers", "app/helpers", "app/mailers", "app/presenters", "app/views"], "scanners"=>[["::I18n::Tasks::Scanners::RubyAstScanner", {"only"=>["*.rb"]}], ["::I18n::Tasks::Scanners::PatternWithScopeScanner", {"exclude"=>["*.rb"], "ignore_lines"=>{"opal"=>"^\\s*#(?!\\si18n-tasks-use)", "haml"=>"^\\s*-\\s*#(?!\\si18n-tasks-use)", "slim"=>"^\\s*(?:-#|/)(?!\\si18n-tasks-use)", "coffee"=>"^\\s*#(?!\\si18n-tasks-use)", "erb"=>"^\\s*<%\\s*#(?!\\si18n-tasks-use)"}}]], "strict"=>true, "exclude"=>["app/assets/images", "app/assets/fonts", "app/assets/videos"]}}:I18n::Tasks::BaseTask
     # ./spec/i18n_spec.rb:22:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:33:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:32:in `block (2 levels) in <top (required)>'

  4) I18n does not have inconsistent interpolations
     Failure/Error: let(:inconsistent_interpolations) { i18n.inconsistent_interpolations }

     NoMethodError:
       undefined method `inconsistent_interpolations' for I18n::Tasks::BaseTask{"base_locale"=>"en", "internal_locale"=>"en", "locales"=>["en", "ru"], "data"=>{"adapter"=>"I18n::Tasks::Data::FileSystem", "read"=>["config/locales/%{locale}.yml", "config/locales/**/*.%{locale}.yml"], "write"=>["config/locales/%{locale}.yml"], "yaml"=>{"write"=>{"line_width"=>-1}}}, "search"=>{"paths"=>["app/"], "relative_roots"=>["app/controllers", "app/helpers", "app/mailers", "app/presenters", "app/views"], "scanners"=>[["::I18n::Tasks::Scanners::RubyAstScanner", {"only"=>["*.rb"]}], ["::I18n::Tasks::Scanners::PatternWithScopeScanner", {"exclude"=>["*.rb"], "ignore_lines"=>{"opal"=>"^\\s*#(?!\\si18n-tasks-use)", "haml"=>"^\\s*-\\s*#(?!\\si18n-tasks-use)", "slim"=>"^\\s*(?:-#|/)(?!\\si18n-tasks-use)", "coffee"=>"^\\s*#(?!\\si18n-tasks-use)", "erb"=>"^\\s*<%\\s*#(?!\\si18n-tasks-use)"}}]], "strict"=>true, "exclude"=>["app/assets/images", "app/assets/fonts", "app/assets/videos"]}}:I18n::Tasks::BaseTask
     # ./spec/i18n_spec.rb:9:in `block (2 levels) in <top (required)>'
     # ./spec/i18n_spec.rb:30:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:33:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:32:in `block (2 levels) in <top (required)>'

```
